export const SENDGRID_CLIENT = 'NOTIFICATIONS_SENDGRID_CLIENT';
export const SENDGRID_FROM_EMAIL = 'NOTIFICATIONS_SENDGRID_FROM_EMAIL';
export const FIREBASE_MESSAGING = 'NOTIFICATIONS_FIREBASE_MESSAGING';
